import { FormEvent, ReactNode, useEffect, useState } from "react";
import { api, errorMessage } from "./api";
import type { AgentResponse, EpicStatus, Evidence, OperationsSummary, Patient, Prediction, QualityResult } from "./types";

function PageHeader({ eyebrow, title, status }: { eyebrow: string; title: string; status?: string }) { return <header><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{status && <div className="live"><i />{status}</div>}</header>; }
function Alert({ children }: { children: ReactNode }) { return <div className="error" role="alert">{children}</div>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><small>{label}</small><strong>{value}</strong><span>{detail}</span></article>; }
function PanelTitle({ eyebrow, title, badge }: { eyebrow: string; title: string; badge: string }) { return <div className="panel-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><span>{badge}</span></div>; }
function format(value?: number) { return value === undefined ? "—" : value.toFixed(3); }

function useLoad<T>(path: string) {
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    const controller = new AbortController();
    api<T>(path, { signal: controller.signal }).then(setData).catch((reason: unknown) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setError(errorMessage(reason)); });
    return () => controller.abort();
  }, [path]);
  return { data, error };
}

function PatientTable({ patients, onSelect }: { patients: Patient[]; onSelect?: (patient: Patient) => void }) {
  return <div className="table-wrap"><table><thead><tr><th>Patient</th><th>Sex</th><th>Anchor age</th><th>Admissions</th><th>Last discharge</th></tr></thead><tbody>{patients.map((patient) => <tr key={patient.subject_id} className={onSelect ? "selectable" : undefined} onClick={() => onSelect?.(patient)}><td><strong>#{patient.subject_id}</strong></td><td>{patient.gender}</td><td>{patient.anchor_age}</td><td>{patient.admission_count ?? "—"}</td><td>{patient.latest_discharge_at?.slice(0, 10) ?? "—"}</td></tr>)}</tbody></table></div>;
}

export function OverviewPage() {
  const patients = useLoad<Patient[]>("/api/v1/patients?limit=8");
  const summary = useLoad<OperationsSummary>("/api/v1/operations/summary");
  const quality = useLoad<QualityResult[]>("/api/v1/data-quality");
  const error = patients.error ?? summary.error ?? quality.error;
  return <><PageHeader eyebrow="Clinical intelligence workspace" title="Operations overview" status={error ? "Service degraded" : "Live API"} />{error && <Alert>{error}</Alert>}<section className="metrics" aria-label="System metrics"><Metric label="Demo patients" value="100" detail="Validated Silver records" /><Metric label="Eligible admissions" value="260" detail="Leakage-aware cohort" /><Metric label="Model PR-AUC" value={format(summary.data?.model.metrics.pr_auc)} detail="Held-out patient split" /><Metric label="Retrieval P@5" value={format(summary.data?.retrieval.evaluation.precision_at_5)} detail="Evaluated intents" /></section><section className="grid"><article className="panel patients"><PanelTitle eyebrow="Patient 360" title="Recent demo cohort" badge="Live API" /><PatientTable patients={patients.data ?? []} /></article><article className="panel quality"><PanelTitle eyebrow="Data reliability" title="Quality gates" badge={quality.data?.every((item) => item.status === "PASS") ? "Passing" : "Checking"} />{(quality.data ?? []).map((item) => <div className="gate" key={`${item.dataset}-${item.rule}`}><i>✓</i><div><strong>{item.dataset}: {item.rule}</strong><small>{item.records_failed} failed of {item.records_checked}</small></div><b>{item.status}</b></div>)}</article><article className="panel search"><PanelTitle eyebrow="Platform run" title="Latest data pipeline" badge={summary.data?.pipeline.status ?? "Loading"} /><div className="run-summary"><div><small>Run ID</small><code>{summary.data?.pipeline.run_id ?? "—"}</code></div><div><small>Engine</small><strong>{summary.data?.pipeline.engine ?? "—"}</strong></div><div><small>Duration</small><strong>{summary.data ? `${summary.data.pipeline.duration_seconds.toFixed(3)} s` : "—"}</strong></div></div></article></section></>;
}

export function PatientsPage() {
  const patients = useLoad<Patient[]>("/api/v1/patients?limit=100");
  const [selected, setSelected] = useState<Patient | null>(null);
  const [detail, setDetail] = useState<Patient | null>(null);
  const [timeline, setTimeline] = useState<Array<Record<string, unknown>>>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!selected) return; Promise.all([api<Patient>(`/api/v1/patients/${selected.subject_id}`), api<Array<Record<string, unknown>>>(`/api/v1/patients/${selected.subject_id}/timeline`)]).then(([patient, events]) => { setDetail(patient); setTimeline(events); }).catch((reason: unknown) => setError(errorMessage(reason))); }, [selected]);
  return <><PageHeader eyebrow="Patient 360" title="Patient explorer" status={`${patients.data?.length ?? 0} records`} />{(patients.error ?? error) && <Alert>{patients.error ?? error}</Alert>}<section className="workspace split"><article className="panel"><PanelTitle eyebrow="Deidentified cohort" title="Select a patient" badge="Gold layer" /><PatientTable patients={patients.data ?? []} onSelect={setSelected} /></article><article className="panel detail"><PanelTitle eyebrow="Longitudinal profile" title={detail ? `Patient #${detail.subject_id}` : "No patient selected"} badge={`${timeline.length} events`} />{!detail ? <p className="empty">Select a row to load the patient profile and admission timeline.</p> : <><dl className="detail-grid">{Object.entries(detail).filter(([, value]) => value !== null).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{String(value)}</dd></div>)}</dl><h3>Admission timeline</h3><div className="timeline">{timeline.map((event, index) => <div key={String(event.hadm_id ?? index)}><i /><p><strong>{String(event.admission_type ?? "Admission")}</strong><span>{String(event.admittime ?? "")}</span><small>{String(event.discharge_location ?? "Discharge location unavailable")}</small></p></div>)}</div></>}</article></section></>;
}

export function RiskPage() {
  const [prediction, setPrediction] = useState<Prediction | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); const fields = new FormData(event.currentTarget); const payload = { age_at_admission: Number(fields.get("age")), length_of_stay_days: Number(fields.get("stay")), prior_admissions: Number(fields.get("prior")), gender: String(fields.get("gender")), admission_type: String(fields.get("type")), insurance: String(fields.get("insurance")) }; try { setPrediction(await api<Prediction>("/api/v1/predict/readmission", { method: "POST", body: JSON.stringify(payload) })); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  return <><PageHeader eyebrow="Decision support" title="Readmission risk" status="Model online" />{error && <Alert>{error}</Alert>}<section className="workspace split form-layout"><article className="panel"><PanelTitle eyebrow="Scoring request" title="Patient factors" badge="Validated input" /><form className="form-grid" onSubmit={submit}><label>Age at admission<input name="age" type="number" min="0" max="120" defaultValue="65" required /></label><label>Length of stay (days)<input name="stay" type="number" min="0" max="365" step="0.1" defaultValue="4" required /></label><label>Prior admissions<input name="prior" type="number" min="0" defaultValue="1" required /></label><label>Gender<select name="gender" defaultValue="F"><option>F</option><option>M</option><option>Other</option></select></label><label>Admission type<select name="type" defaultValue="EW EMER."><option>EW EMER.</option><option>URGENT</option><option>ELECTIVE</option></select></label><label>Insurance<select name="insurance" defaultValue="Medicare"><option>Medicare</option><option>Medicaid</option><option>Other</option></select></label><button disabled={loading}>{loading ? "Scoring…" : "Calculate risk"}</button></form></article><article className="panel result-card"><PanelTitle eyebrow="Model response" title="Risk assessment" badge={prediction?.risk_level ?? "Awaiting input"} />{prediction ? <><div className="risk-score">{(prediction.risk_probability * 100).toFixed(1)}<small>%</small></div><p>Threshold: {(prediction.threshold * 100).toFixed(1)}%</p><code>{prediction.model_run_id}</code><div className="notice">{prediction.disclaimer}</div></> : <p className="empty">Submit validated features to receive a traceable model response.</p>}</article></section></>;
}

function SearchForm({ endpoint, assistant = false }: { endpoint: string; assistant?: boolean }) {
  const [query, setQuery] = useState(assistant ? "Summarize emergency admissions" : "emergency hospital admission"); const [subjectId, setSubjectId] = useState(""); const [evidence, setEvidence] = useState<Evidence[]>([]); const [agent, setAgent] = useState<AgentResponse | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { if (assistant) setAgent(await api<AgentResponse>(endpoint, { method: "POST", body: JSON.stringify({ question: query, subject_id: subjectId ? Number(subjectId) : null }) })); else { const result = await api<{ results: Evidence[] }>(endpoint, { method: "POST", body: JSON.stringify({ query, limit: 10, subject_id: subjectId ? Number(subjectId) : null }) }); setEvidence(result.results); } } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }
  return <>{error && <Alert>{error}</Alert>}<article className="panel"><form className="query-form" onSubmit={submit}><label>{assistant ? "Question" : "Search indexed admission context"}<textarea value={query} onChange={(event) => setQuery(event.target.value)} minLength={2} required /></label><label>Optional patient ID<input value={subjectId} onChange={(event) => setSubjectId(event.target.value)} inputMode="numeric" placeholder="e.g. 10014729" /></label><button disabled={loading}>{loading ? "Working…" : assistant ? "Ask assistant" : "Search evidence"}</button></form></article>{assistant && agent && <article className="panel answer"><PanelTitle eyebrow="Grounded response" title="Assistant answer" badge={agent.grounded ? "Grounded" : "Insufficient evidence"} /><p>{agent.answer}</p><div className="audit"><span>Tools: {agent.tools_executed.join(", ")}</span><code>Audit {agent.audit_id}</code></div></article>}{!assistant && evidence.length > 0 && <section className="evidence">{evidence.map((item) => <article key={item.document_id}><div><strong>{item.document_id}</strong><span>{item.score.toFixed(3)}</span></div><p>{item.text}</p><small>{item.metadata.source} · admission {item.metadata.hadm_id} · patient {item.metadata.subject_id}</small></article>)}</section>}</>;
}

export function EvidencePage() { return <><PageHeader eyebrow="Grounded retrieval" title="Clinical evidence search" status="FAISS index" /><SearchForm endpoint="/api/v1/search" /></>; }
export function AssistantPage() { return <><PageHeader eyebrow="Auditable orchestration" title="AI assistant" status="Evidence constrained" /><SearchForm endpoint="/api/v1/agent/query" assistant /></>; }
export function DataQualityPage() { const quality = useLoad<QualityResult[]>("/api/v1/data-quality"); return <><PageHeader eyebrow="Data reliability" title="Data quality" status={quality.data?.every((item) => item.status === "PASS") ? "All gates passing" : "Loading checks"} />{quality.error && <Alert>{quality.error}</Alert>}<article className="panel"><PanelTitle eyebrow="Latest pipeline run" title="Validation results" badge={`${quality.data?.length ?? 0} checks`} /><div className="table-wrap"><table><thead><tr><th>Dataset</th><th>Rule</th><th>Severity</th><th>Checked</th><th>Failed</th><th>Status</th><th>Executed</th></tr></thead><tbody>{(quality.data ?? []).map((item) => <tr key={`${item.dataset}-${item.rule}`}><td>{item.dataset}</td><td><code>{item.rule}</code></td><td>{item.severity}</td><td>{item.records_checked}</td><td>{item.records_failed}</td><td><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span></td><td>{new Date(item.execution_timestamp).toLocaleString()}</td></tr>)}</tbody></table></div></article></>; }
export function MonitoringPage() { const summary = useLoad<OperationsSummary>("/api/v1/operations/summary"); const data = summary.data; const metrics = data?.model.metrics; return <><PageHeader eyebrow="ML operations" title="Model monitoring" status={data ? "Artifacts loaded" : "Loading artifacts"} />{summary.error && <Alert>{summary.error}</Alert>}<section className="metrics"><Metric label="PR-AUC" value={format(metrics?.pr_auc)} detail="Primary imbalance metric" /><Metric label="ROC-AUC" value={format(metrics?.roc_auc)} detail="Held-out patient split" /><Metric label="Brier score" value={format(metrics?.brier_score)} detail="Probability calibration" /><Metric label="Threshold" value={format(data?.model.threshold)} detail="Operating point" /></section><section className="workspace split"><article className="panel"><PanelTitle eyebrow="Evaluation" title="Model performance" badge="Test split" /><dl className="metric-list">{metrics && Object.entries(metrics).map(([name, value]) => <div key={name}><dt>{name.replaceAll("_", " ")}</dt><dd>{value.toFixed(4)}</dd></div>)}</dl></article><article className="panel"><PanelTitle eyebrow="Lineage" title="Model artifact" badge="Traceable" /><dl className="detail-grid"><div><dt>Run ID</dt><dd><code>{data?.model.run_id ?? "—"}</code></dd></div><div><dt>Trained</dt><dd>{data ? new Date(data.model.trained_at).toLocaleString() : "—"}</dd></div><div><dt>Training time</dt><dd>{data ? `${data.model.duration_seconds.toFixed(2)} s` : "—"}</dd></div><div><dt>Retrieval documents</dt><dd>{data?.retrieval.index.documents ?? "—"}</dd></div><div><dt>Embedding dimensions</dt><dd>{data?.retrieval.index.dimensions ?? "—"}</dd></div><div><dt>Retrieval latency</dt><dd>{data ? `${data.retrieval.evaluation.mean_latency_ms.toFixed(2)} ms` : "—"}</dd></div></dl></article></section></>; }

export function EHRIntegrationPage() {
  const status = useLoad<EpicStatus>("/api/v1/integrations/epic/status");
  const connected = new URLSearchParams(window.location.search).get("connected") === "true";
  return <><PageHeader eyebrow="Clinical interoperability" title="Epic EHR integration" status={connected ? "Epic session connected" : status.data?.enabled ? "SMART enabled" : "Setup required"} />{status.error && <Alert>{status.error}</Alert>}<section className="workspace split"><article className="panel"><PanelTitle eyebrow="SMART on FHIR" title="Epic connection" badge={status.data?.configured ? "Configured" : "Not configured"} /><dl className="detail-grid"><div><dt>Provider</dt><dd>{status.data?.provider ?? "Epic"}</dd></div><div><dt>Standard</dt><dd>{status.data?.standard ?? "FHIR R4 / SMART App Launch"}</dd></div><div><dt>FHIR base URL</dt><dd><code>{status.data?.fhir_base_url ?? "Loading…"}</code></dd></div><div><dt>PHI mode</dt><dd>{status.data?.live_phi_allowed ? "Allowed" : "Deidentified/sandbox only"}</dd></div></dl>{status.data?.enabled ? <button className="connect" onClick={() => { window.location.href = "/api/v1/integrations/epic/launch"; }}>Connect to Epic</button> : <div className="notice">Register a non-production app in Epic on FHIR, then set EPIC_CLIENT_ID, EPIC_STATE_ENCRYPTION_KEY, and EPIC_SMART_ENABLED=true. Until then, live Epic access remains safely disabled.</div>}</article><article className="panel"><PanelTitle eyebrow="Security posture" title="Healthcare safeguards" badge="Foundation" /><div className="control-list">{["OAuth 2.0 authorization code with PKCE", "Strict Epic issuer allowlist", "Single-use, expiring launch state", "Encrypted token storage in Redis", "HttpOnly and SameSite session cookie", "FHIR resource and pagination validation", "No access tokens returned to the browser", "Deidentified data is the default"].map((control) => <div key={control}><i>✓</i><span>{control}</span></div>)}</div><div className="notice warning"><strong>Not a HIPAA certification.</strong> Production authorization still requires a formal risk assessment, BAA-covered hosting, organizational policies, audit review, incident response, and customer-specific Epic approval.</div></article></section></>;
}
